apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: requests
  name: requests
  namespace: team-a
spec:
  replicas: 5
  selector:
    matchLabels:
      app: requests
  template:
    metadata:
      labels:
        app: requests
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        command:
        - /bin/sh
        - -c
        - stress --vm 1 --vm-bytes 512M